target: models.class_util.UNet
params:
  in_channels: 3
  model_channels: 16
  out_channels: 3
  num_res_blocks: 2
  attention_resolutions: []
  dropout: 0.0
  num_classes: 3
  channel_mult: 
  - 1
  - 1
  - 2
  - 2
  num_head_channels: 16

   